language: node_js

node_js:
  - 6

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fathom"
    template:
      - "[%{repository_name} %{branch} %{result}] \"%{commit_subject}\" by %{author}"
      - "Changes: %{compare_url}"
      - "Build details: %{build_url}"
